### ISSUE TITLE
有时候会报空指针错误

### ISSUE THREAD

**Issue by ichynul** [chiemy/JellyViewPager#2]
困扰了我一天，第二天睡了一觉起来，把控件的源代码改了一下就好了。
就是在 onLayout 里面加了currentView 是否为空的判断。具体的为什么会空，我也搞不清楚（开始的时候是正常的，但加了业务就出问题）。
这样一改，xmlLayout里面也好看多了，没有错误提示。
@Override
    protected void onLayout(boolean arg0, int arg1, int arg2, int arg3, int arg4)
    {
        super.onLayout(arg0, arg1, arg2, arg3, arg4);
        if (currentView == null)
        {
            currentView = getCurrentView();
            if (currentView != null)
            {
                ViewHelper.setScaleX(currentView, MAX_SCALE);
                ViewHelper.setScaleY(currentView, MAX_SCALE);
                currentView.getHitRect(currentViewRect);
            }
        }
        mHeight = getHeight();
        mWidth = getWidth();
        OUT_DISTANCE_BOUDARY = MAX_SCALE \* mHeight / 3;
    }

**Comment by chiemy** [comment]
谢谢提供的宝贵意见
